# Generated by Django 5.1.6 on 2025-03-03 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mijozlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100, verbose_name='ism')),
                ('familiya', models.CharField(max_length=100, verbose_name='familiya')),
                ('telefon', models.CharField(max_length=20, unique=True, verbose_name='telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
                'db_table': 'mijozlar',
            },
        ),
        migrations.CreateModel(
            name='Restoran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255, verbose_name='nomi')),
                ('manzil', models.TextField(verbose_name='manzil')),
                ('telefon', models.CharField(max_length=20, verbose_name='telefon')),
                ('ish_vaqti', models.CharField(max_length=100, verbose_name='ish vaqti')),
            ],
            options={
                'verbose_name': 'Restoran',
                'verbose_name_plural': 'Restoran',
                'db_table': 'restoran',
            },
        ),
        migrations.CreateModel(
            name='Taomlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255, verbose_name='nomi')),
                ('narx', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='narx')),
                ('tavsif', models.TextField(blank=True, null=True, verbose_name='tavsif')),
            ],
            options={
                'verbose_name': 'Taom',
                'verbose_name_plural': 'Taomlar',
                'db_table': 'taomlar',
            },
        ),
        migrations.CreateModel(
            name='MoliyaviyHisobot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tushum', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='tushum')),
                ('xarajat', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='xarajat')),
                ('sanasi', models.DateField(auto_now_add=True, verbose_name='sanasi')),
                ('restoran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.restoran', verbose_name='restoran')),
            ],
            options={
                'verbose_name': 'Moliyaviy Hisobot',
                'verbose_name_plural': 'Moliyaviy Hisobotlar',
                'db_table': 'moliyaviy_hisobot',
            },
        ),
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umumiy_narx', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='umumiy narx')),
                ('status', models.CharField(choices=[('Yangi', 'Yangi'), ('Tayyorlanmoqda', 'Tayyorlanmoqda'), ('Yakunlangan', 'Yakunlangan')], default='Yangi', max_length=50)),
                ('sana', models.DateTimeField(auto_now_add=True, verbose_name='sana')),
                ('mijoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mijozlar', verbose_name='mijoz')),
                ('restoran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.restoran', verbose_name='restoran')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'db_table': 'buyurtmalar',
            },
        ),
        migrations.CreateModel(
            name='BuyurtmaTafsiloti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soni', models.PositiveIntegerField(verbose_name='soni')),
                ('buyurtma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.buyurtma', verbose_name='buyurtma')),
                ('taom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.taomlar', verbose_name='mahsulot')),
            ],
            options={
                'verbose_name': 'Buyurtma Tafsiloti',
                'verbose_name_plural': 'Buyurtma Tafsilotlari',
                'db_table': 'buyurtma_tafsiloti',
            },
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='taomlar',
            field=models.ManyToManyField(through='main.BuyurtmaTafsiloti', to='main.taomlar', verbose_name='mahsulotlar'),
        ),
        migrations.CreateModel(
            name='Xodimlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100, verbose_name='ism')),
                ('familiya', models.CharField(max_length=100, verbose_name='familiya')),
                ('lavozim', models.CharField(max_length=100, verbose_name='lavozim')),
                ('telefon', models.CharField(max_length=20, unique=True, verbose_name='telefon')),
                ('restoran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.restoran', verbose_name='restoran')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'db_table': 'xodimlar',
            },
        ),
    ]
