# Generated by Django 5.1.6 on 2025-03-03 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mijozlar',
            new_name='Mijoz',
        ),
    ]
