# Generated by Django 5.1.5 on 2025-03-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_mijozlar_mijoz'),
    ]

    operations = [
        migrations.AddField(
            model_name='taomlar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='../media/images', verbose_name='image'),
        ),
    ]
