# Generated by Django 5.1.6 on 2025-03-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_taomlar_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvqatMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taom_nomi', models.CharField(max_length=255, verbose_name='taom nomi')),
                ('sotilgan_miqdor', models.IntegerField()),
                ('sertifikat', models.BooleanField(default=False, verbose_name='sertifikat')),
                ('oxirgi_yangilanish', models.DateField()),
            ],
            options={
                'verbose_name': 'Ovqat Monitoring',
                'verbose_name_plural': 'Ovqat Monitoringlar',
                'db_table': 'ovqat_monitoring',
            },
        ),
        migrations.CreateModel(
            name='Sertifikat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahsulot_nomi', models.CharField(max_length=255, verbose_name='mahsulot')),
                ('tasdiqlovchi_organ', models.CharField(max_length=255, verbose_name='tasdiqlovchi')),
                ('berilgan_sana', models.DateField()),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
                'db_table': 'sertifikat',
            },
        ),
        migrations.RemoveField(
            model_name='buyurtmatafsiloti',
            name='soni',
        ),
        migrations.RemoveField(
            model_name='taomlar',
            name='narx',
        ),
        migrations.RemoveField(
            model_name='taomlar',
            name='nomi',
        ),
        migrations.RemoveField(
            model_name='taomlar',
            name='tavsif',
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='manzil',
            field=models.TextField(blank=True, null=True, verbose_name='manzil'),
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='miqdor',
            field=models.IntegerField(blank=True, null=True, verbose_name='miqdor'),
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='telefon'),
        ),
        migrations.AddField(
            model_name='buyurtmatafsiloti',
            name='miqdor',
            field=models.IntegerField(blank=True, null=True, verbose_name='miqdor'),
        ),
        migrations.AddField(
            model_name='buyurtmatafsiloti',
            name='narx',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='taomlar',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='taomlar',
            name='taom_narxi',
            field=models.IntegerField(blank=True, null=True, verbose_name='taom_narxi'),
        ),
        migrations.AddField(
            model_name='taomlar',
            name='taom_nomi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='taom_nomi'),
        ),
        migrations.AlterField(
            model_name='taomlar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image'),
        ),
    ]
