# Generated by Django 5.1.7 on 2025-03-16 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ovqatmonitoring_sertifikat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyurtma',
            name='sana',
        ),
        migrations.RemoveField(
            model_name='buyurtma',
            name='status',
        ),
        migrations.RemoveField(
            model_name='buyurtma',
            name='umumiy_narx',
        ),
    ]
