# Generated by Django 5.1.7 on 2025-03-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_taomlar_taom_narxi_taomlar_narx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taomlar',
            old_name='taom_nomi',
            new_name='nomi',
        ),
        migrations.RemoveField(
            model_name='taomlar',
            name='description',
        ),
        migrations.AddField(
            model_name='taomlar',
            name='tavsif',
            field=models.TextField(blank=True, null=True, verbose_name='tavsif'),
        ),
    ]
