# Generated by Django 5.1.7 on 2025-03-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_taom_nomi_taomlar_nomi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taomlar',
            name='nomi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nomi'),
        ),
    ]
