# Generated by Django 5.1.7 on 2025-03-16 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_taomlar_nomi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyurtma',
            name='telefon',
        ),
    ]
