# Generated by Django 5.1.5 on 2025-03-16 15:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_buyurtma_telefon'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyurtma',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
