# Generated by Django 5.1.5 on 2025-03-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_buyurtma_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyurtma',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
