# Generated by Django 4.2.20 on 2025-03-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_buyurtma_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='restoran',
            name='image',
            field=models.ImageField(default=None, upload_to='images/', verbose_name='image'),
        ),
    ]
