# Generated by Django 4.2.20 on 2025-03-20 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_restoran_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restoran',
            name='image',
        ),
    ]
