# Generated by Django 4.2.20 on 2025-03-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_restoran_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='xodimlar',
            name='ish_vaqti',
            field=models.CharField(blank=True, default='09:00 - 18:00', max_length=100, null=True, verbose_name='ish vaqti'),
        ),
        migrations.AlterField(
            model_name='restoran',
            name='image',
            field=models.ImageField(default='09:00 - 18:00', upload_to='images/', verbose_name='image'),
            preserve_default=False,
        ),
    ]
