# Generated by Django 4.2.20 on 2025-03-20 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_xodimlar_telefon_alter_xodimlar_ish_vaqti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovqatmonitoring',
            name='sertifikat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sertifikat', verbose_name='sertifikat'),
        ),
    ]
