# Generated by Django 4.2.20 on 2025-03-20 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_ovqatmonitoring_sertifikat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovqatmonitoring',
            name='taom_nomi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.taomlar', verbose_name='taom'),
        ),
    ]
