# Generated by Django 5.1.7 on 2025-03-20 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_ovqatmonitoring_taom_nomi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ovqatmonitoring',
            old_name='taom_nomi',
            new_name='taom',
        ),
    ]
