# Generated by Django 5.1.7 on 2025-03-21 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_rename_taom_nomi_ovqatmonitoring_taom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyurtma',
            name='mijoz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='mijoz'),
        ),
        migrations.DeleteModel(
            name='Mijoz',
        ),
    ]
