# Generated by Django 5.1.7 on 2025-04-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_usermenuchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='taomlar',
            name='restoranlar',
            field=models.ManyToManyField(related_name='taomlar', to='main.restoran', verbose_name='restoranlar'),
        ),
    ]
