# Generated by Django 5.1.7 on 2025-04-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_taomlar_restoranlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyurtma',
            name='delivery_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='distance_km',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='payment_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='promo_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buyurtma',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
