# Generated by Django 5.1.7 on 2025-04-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_buyurtma_delivery_price_buyurtma_distance_km_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyurtma',
            name='delivery_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='distance_km',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='payment_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='total_price',
            field=models.IntegerField(),
        ),
    ]
