# Generated by Django 5.1.7 on 2025-04-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_buyurtma_delivery_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taomlar',
            name='narx',
            field=models.IntegerField(verbose_name='narx'),
        ),
    ]
