# Generated by Django 5.1.7 on 2025-04-29 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_taomlar_narx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyurtma',
            name='miqdor',
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10, verbose_name='yetkazib berish narxi'),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='distance_km',
            field=models.FloatField(blank=True, default='', null=True, verbose_name='masofa'),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='manzil',
            field=models.TextField(blank=True, default='', null=True, verbose_name='manzil'),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='mijoz',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='mijoz'),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='payment_type',
            field=models.CharField(default='', max_length=50, verbose_name='to‘lov turi'),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='promo_code',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='promokod'),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='restoran',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.restoran', verbose_name='restoran'),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='taomlar',
            field=models.ManyToManyField(default='', through='main.BuyurtmaTafsiloti', to='main.taomlar', verbose_name='mahsulotlar'),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10, verbose_name='umumiy narx'),
        ),
        migrations.AlterField(
            model_name='buyurtmatafsiloti',
            name='buyurtma',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.buyurtma', verbose_name='buyurtma'),
        ),
        migrations.AlterField(
            model_name='buyurtmatafsiloti',
            name='miqdor',
            field=models.IntegerField(default='', verbose_name='miqdor'),
        ),
        migrations.AlterField(
            model_name='buyurtmatafsiloti',
            name='narx',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10, verbose_name='narx'),
        ),
        migrations.AlterField(
            model_name='buyurtmatafsiloti',
            name='taom',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.taomlar', verbose_name='mahsulot'),
        ),
        migrations.AlterField(
            model_name='restoran',
            name='image',
            field=models.ImageField(default='', upload_to='images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='restoran',
            name='ish_vaqti',
            field=models.CharField(default='', max_length=100, verbose_name='ish vaqti'),
        ),
        migrations.AlterField(
            model_name='restoran',
            name='manzil',
            field=models.TextField(default='', verbose_name='manzil'),
        ),
        migrations.AlterField(
            model_name='restoran',
            name='nomi',
            field=models.CharField(default='', max_length=255, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='restoran',
            name='telefon',
            field=models.CharField(default='', max_length=20, verbose_name='telefon'),
        ),
        migrations.AlterField(
            model_name='taomlar',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='taomlar',
            name='narx',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10, verbose_name='narx'),
        ),
        migrations.AlterField(
            model_name='taomlar',
            name='nomi',
            field=models.CharField(default='', max_length=255, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='taomlar',
            name='restoranlar',
            field=models.ManyToManyField(default='', related_name='taomlar', to='main.restoran', verbose_name='restoranlar'),
        ),
        migrations.AlterField(
            model_name='taomlar',
            name='tavsif',
            field=models.TextField(blank=True, default='', null=True, verbose_name='tavsif'),
        ),
        migrations.AlterField(
            model_name='xodimlar',
            name='familiya',
            field=models.CharField(default='', max_length=100, verbose_name='familiya'),
        ),
        migrations.AlterField(
            model_name='xodimlar',
            name='ish_vaqti',
            field=models.CharField(default='', max_length=100, verbose_name='ish vaqti'),
        ),
        migrations.AlterField(
            model_name='xodimlar',
            name='ism',
            field=models.CharField(default='', max_length=100, verbose_name='ism'),
        ),
        migrations.AlterField(
            model_name='xodimlar',
            name='lavozim',
            field=models.CharField(default='', max_length=100, verbose_name='lavozim'),
        ),
        migrations.AlterField(
            model_name='xodimlar',
            name='restoran',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.restoran', verbose_name='restoran'),
        ),
    ]
