# Generated by Django 5.1.7 on 2025-04-29 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_buyurtma_miqdor_alter_buyurtma_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyurtma',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=11, max_digits=10, verbose_name='yetkazib berish narxi'),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='distance_km',
            field=models.FloatField(blank=True, default=1, null=True, verbose_name='masofa'),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='mijoz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='mijoz'),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='restoran',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='main.restoran', verbose_name='restoran'),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='taomlar',
            field=models.ManyToManyField(default=1, through='main.BuyurtmaTafsiloti', to='main.taomlar', verbose_name='mahsulotlar'),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='umumiy narx'),
        ),
        migrations.AlterField(
            model_name='buyurtmatafsiloti',
            name='buyurtma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.buyurtma', verbose_name='buyurtma'),
        ),
        migrations.AlterField(
            model_name='buyurtmatafsiloti',
            name='miqdor',
            field=models.IntegerField(default=0, verbose_name='miqdor'),
        ),
        migrations.AlterField(
            model_name='buyurtmatafsiloti',
            name='narx',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='narx'),
        ),
        migrations.AlterField(
            model_name='buyurtmatafsiloti',
            name='taom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.taomlar', verbose_name='mahsulot'),
        ),
        migrations.AlterField(
            model_name='taomlar',
            name='narx',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='narx'),
        ),
        migrations.AlterField(
            model_name='taomlar',
            name='restoranlar',
            field=models.ManyToManyField(default=1, related_name='taomlar', to='main.restoran', verbose_name='restoranlar'),
        ),
        migrations.AlterField(
            model_name='xodimlar',
            name='restoran',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.restoran', verbose_name='restoran'),
        ),
    ]
