# Generated by Django 5.1.7 on 2025-04-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_buyurtma_delivery_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyurtmatafsiloti',
            name='miqdor',
            field=models.IntegerField(verbose_name='miqdor'),
        ),
    ]
