# Generated by Django 5.1.7 on 2025-04-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_buyurtmatafsiloti_miqdor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyurtmatafsiloti',
            name='miqdor',
            field=models.IntegerField(default=0, verbose_name='miqdor'),
        ),
    ]
