# Generated by Django 5.1.7 on 2025-04-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_buyurtma_delivery_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyurtma',
            name='order_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
