# Generated by Django 5.1.7 on 2025-04-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_buyurtma_order_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kuryer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('familiya', models.CharField(max_length=50)),
                ('telefon', models.CharField(max_length=20)),
                ('band', models.BooleanField(default=False)),
            ],
        ),
    ]
