# Generated by Django 5.1.7 on 2025-04-29 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_kuryer'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyurtma',
            name='kuryer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.kuryer'),
        ),
    ]
