# Generated by Django 5.1.7 on 2025-04-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_buyurtma_kuryer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restoran',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='restoran',
            name='ish_vaqti',
            field=models.CharField(max_length=100, verbose_name='ish vaqti'),
        ),
        migrations.AlterField(
            model_name='restoran',
            name='manzil',
            field=models.TextField(verbose_name='manzil'),
        ),
        migrations.AlterField(
            model_name='restoran',
            name='nomi',
            field=models.CharField(max_length=255, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='restoran',
            name='telefon',
            field=models.CharField(max_length=20, verbose_name='telefon'),
        ),
    ]
