# Generated by Django 5.1.7 on 2025-04-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_restoran_image_alter_restoran_ish_vaqti_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyurtma',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('assigned', 'Kuryer Belgilandi'), ('cancelled', 'Bekor Qilindi'), ('delivered', 'Yetkazib Berildi')], default='pending', max_length=20, verbose_name='status'),
        ),
    ]
