# Generated by Django 5.2 on 2025-05-14 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_buyurtma_additional_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='kuryer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='kuryer',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='kuryer',
            name='band',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='kuryer',
            name='telefon',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Telefon raqami to'g'ri formatda bo'lishi kerak, masalan: +998901234567", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
