# Generated by Django 5.2 on 2025-05-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_kuryer_created_at_alter_kuryer_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kuryer',
            name='band',
            field=models.BooleanField(default=False),
        ),
    ]
