# Generated by Django 5.2 on 2025-05-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_alter_kuryer_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyurtma',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
