# Generated by Django 5.1.7 on 2025-04-17 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermenuchoice',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='usermenuchoice',
            name='user',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='UserMenuChoice',
        ),
    ]
